// cx — a browsable command library and shortcut manager.
//
// Reads YAML "packs" from a config dir (default $XDG_CONFIG_HOME/cx, override
// with $CX_DIR), merges them into one tree of categories/commands, and lets you
// browse or fuzzy-search them in a TUI. Discovery-first: you search over name +
// description + command, so you can find a command by *what it does*.
//
// Picking a command prints it to stdout; the shell wrapper puts it on your
// prompt (editable) so you review before running.
//
// Full CRUD lives in the TUI (new/edit/delete commands, set aliases) via modal
// dialogs. cx owns the pack files: a command's alias is just an inline `alias:`
// field. Every alias is compiled to $CX_DIR/aliases.sh, which your shell
// sources — so a new shell has the alias immediately, no rebuild.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"
	"unicode"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
	"github.com/muesli/termenv"
	"gopkg.in/yaml.v3"
)

const aliasesFileName = "aliases.sh"

// Node is a category (has Items) or a command (has Cmd). A pack file unmarshals
// into one top-level Node whose Items are its entries.
type Node struct {
	Name  string  `yaml:"name"`
	Desc  string  `yaml:"desc,omitempty"`
	Cmd   string  `yaml:"cmd,omitempty"`
	Icon  string  `yaml:"icon,omitempty"`  // Nerd Font glyph; falls back to a default
	Alias string  `yaml:"alias,omitempty"` // optional shell alias for this command
	Items []*Node `yaml:"items,omitempty"`
}

func (n *Node) isLeaf() bool { return len(n.Items) == 0 && strings.TrimSpace(n.Cmd) != "" }

// Nerd Font fallback glyphs (FontAwesome range — present in every Nerd Font).
const (
	iconFolder = "\uf07b" // nf-fa-folder
	iconCmd    = "\uf120" // nf-fa-terminal
	iconStar   = "\uf005" // nf-fa-star
)

// glyph returns the node's icon, or a sensible default by kind.
func (n *Node) glyph() string {
	if n.Icon != "" {
		return n.Icon
	}
	if n.isLeaf() {
		return iconCmd
	}
	return iconFolder
}

// --- loading -------------------------------------------------------------

// pack is one YAML file: its top-level category plus the path to write back to.
// cx owns the pack files. Commands live in them, and a command's alias is just
// an inline `alias:` field — no separate overlay, what you see is the file.
type pack struct {
	file string
	root *Node
}

// loadPacks loads every *.yaml file in dir as one pack.
func loadPacks(dir string) ([]*pack, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var files []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		if ext := strings.ToLower(filepath.Ext(e.Name())); ext == ".yaml" || ext == ".yml" {
			files = append(files, e.Name())
		}
	}
	sort.Strings(files)
	var packs []*pack
	for _, f := range files {
		path := filepath.Join(dir, f)
		b, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		var n Node
		if err := yaml.Unmarshal(b, &n); err != nil {
			return nil, fmt.Errorf("%s: %w", f, err)
		}
		if n.Name == "" {
			n.Name = strings.TrimSuffix(f, filepath.Ext(f))
		}
		packs = append(packs, &pack{file: path, root: &n})
	}
	return packs, nil
}

func savePack(p *pack) error {
	b, err := yaml.Marshal(p.root)
	if err != nil {
		return err
	}
	header := "# Managed by cx — edit here or via the cx TUI.\n"
	return os.WriteFile(p.file, append([]byte(header), b...), 0o644)
}

type aliasPair struct {
	name  string
	cmd   string
	owner string
}

// collectAliases gathers (aliasName, cmd) for every leaf carrying an alias.
func collectAliases(n *Node, prefix string, out *[]aliasPair) error {
	for _, c := range n.Items {
		p := c.Name
		if prefix != "" {
			p = prefix + " › " + c.Name
		}
		if c.isLeaf() {
			alias := strings.TrimSpace(c.Alias)
			if alias != "" {
				if !validAlias(alias) {
					return fmt.Errorf("invalid alias %q on %s", alias, p)
				}
				*out = append(*out, aliasPair{name: alias, cmd: c.Cmd, owner: p})
			}
		} else {
			if err := collectAliases(c, p, out); err != nil {
				return err
			}
		}
	}
	return nil
}

// writeAliases compiles every command alias in the tree into aliases.sh.
func writeAliases(path string, root *Node) error {
	var pairs []aliasPair
	if err := collectAliases(root, "", &pairs); err != nil {
		return err
	}
	seen := map[string]string{}
	for _, p := range pairs {
		if owner, ok := seen[p.name]; ok {
			return fmt.Errorf("duplicate alias %q on %s (already used by %s)", p.name, p.owner, owner)
		}
		seen[p.name] = p.owner
	}
	sort.Slice(pairs, func(i, j int) bool { return pairs[i].name < pairs[j].name })
	var b strings.Builder
	b.WriteString("# Generated by cx from your command packs — do not edit by hand.\n")
	b.WriteString("# Sourced by your shell; run `cx --gen-aliases` to refresh.\n")
	for _, p := range pairs {
		esc := strings.ReplaceAll(p.cmd, "'", `'\''`)
		fmt.Fprintf(&b, "alias %s='%s'\n", p.name, esc)
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func validAlias(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		if i == 0 {
			if !aliasStart(r) {
				return false
			}
			continue
		}
		if !aliasChar(r) {
			return false
		}
	}
	return true
}

func aliasStart(r rune) bool {
	return r == '_' || ('a' <= r && r <= 'z') || ('A' <= r && r <= 'Z')
}

func aliasChar(r rune) bool {
	return aliasStart(r) || ('0' <= r && r <= '9') || r == '-' || r == '.'
}

// slug turns a display name into a reasonable default alias name.
func slug(s string) string {
	var b strings.Builder
	prevDash := false
	for _, r := range strings.ToLower(s) {
		switch {
		case unicode.IsLetter(r) || unicode.IsDigit(r):
			b.WriteRune(r)
			prevDash = false
		case !prevDash:
			b.WriteRune('-')
			prevDash = true
		}
	}
	return strings.Trim(b.String(), "-")
}

// --- fuzzy matching ------------------------------------------------------

func fuzzy(pattern, s string) (bool, int) {
	if pattern == "" {
		return true, 0
	}
	p := strings.ToLower(pattern)
	t := strings.ToLower(s)
	score, pi, last := 0, 0, -1
	for ti := 0; ti < len(t) && pi < len(p); ti++ {
		if t[ti] == p[pi] {
			if last >= 0 {
				score += ti - last
			} else {
				score += ti
			}
			last = ti
			pi++
		}
	}
	return pi == len(p), score
}

// --- rows ----------------------------------------------------------------

type row struct {
	node    *Node
	path    string
	isGroup bool
}

func collectLeaves(n *Node, prefix string, out *[]row) {
	for _, c := range n.Items {
		p := c.Name
		if prefix != "" {
			p = prefix + " › " + c.Name
		}
		if c.isLeaf() {
			*out = append(*out, row{node: c, path: p})
		} else {
			collectLeaves(c, p, out)
		}
	}
}

// --- model ---------------------------------------------------------------

type dlgKind int

const (
	dlgNone    dlgKind = iota
	dlgAlias           // set/edit the selected command's alias
	dlgNewCmd          // create a command in the current category
	dlgEditCmd         // edit the selected command
	dlgNewCat          // create a category (sub-category or new pack)
	dlgEditCat         // edit the selected category
	dlgDelCmd          // delete the selected command or category (confirm)
)

type fieldKind int

const (
	fText fieldKind = iota
	fButton
)

// field is one focusable row in a dialog: a text input or an action button.
type field struct {
	kind   fieldKind
	label  string // label (text field) or caption (button)
	value  string // text content
	action string // button action id
	alias  bool   // text field holding an alias name (gets a live conflict hint)
}

// dialog is an active modal popup with focusable fields, driven by the arrows.
type dialog struct {
	kind   dlgKind
	title  string
	node   *Node // context: the command, or the category a new command goes into
	fields []field
	focus  int
}

type model struct {
	root     *Node
	dir      string
	packs    []*pack         // source files, so edits write back to the right pack
	external map[string]bool // alias names already active in the shell (via $CX_ALIASES)

	stack  []*Node
	cursor int
	filter string
	rows   []row
	w, h   int

	dlg    dialog // active popup (dlgNone = none)
	status string // transient message

	frame  int // animation tick for the logo gradient
	chosen string
}

type tickMsg struct{}

func tick() tea.Cmd {
	return tea.Tick(time.Second/10, func(time.Time) tea.Msg { return tickMsg{} })
}

func newModel(root *Node, dir string, packs []*pack, external map[string]bool) *model {
	m := &model{root: root, dir: dir, packs: packs, external: external, stack: []*Node{root}}
	m.recompute()
	return m
}

// aliasUsedBy finds a command (other than except) that already owns this alias.
func (m *model) aliasUsedBy(name string, except *Node) *Node {
	var found *Node
	var walk func(n *Node)
	walk = func(n *Node) {
		for _, c := range n.Items {
			if c.isLeaf() {
				if found == nil && c != except && c.Alias == name {
					found = c
				}
			} else {
				walk(c)
			}
		}
	}
	walk(m.root)
	return found
}

// nameStatus classifies a candidate alias name for live feedback in the dialog:
//
//	"" invalid · "current" unchanged · "dup" used by another command ·
//	"conflict" used by an alias outside cx · "new" free.
func (m *model) nameStatus(name string, except *Node) string {
	name = strings.TrimSpace(name)
	if !validAlias(name) {
		return ""
	}
	if except != nil && except.Alias == name {
		return "current"
	}
	if m.aliasUsedBy(name, except) != nil {
		return "dup"
	}
	if m.external[name] {
		return "conflict"
	}
	return "new"
}

func (m *model) cur() *Node { return m.stack[len(m.stack)-1] }

func (m *model) recompute() {
	m.rows = m.rows[:0]
	if m.filter == "" {
		for _, c := range m.cur().Items {
			m.rows = append(m.rows, row{node: c, isGroup: !c.isLeaf()})
		}
	} else {
		var all []row
		collectLeaves(m.cur(), "", &all)
		type scored struct {
			r     row
			score int
		}
		var hits []scored
		for _, r := range all {
			hay := r.node.Name + " " + r.node.Desc + " " + r.node.Cmd + " " + r.node.Alias + " " + r.path
			if ok, sc := fuzzy(m.filter, hay); ok {
				hits = append(hits, scored{r, sc})
			}
		}
		sort.SliceStable(hits, func(i, j int) bool { return hits[i].score < hits[j].score })
		for _, s := range hits {
			m.rows = append(m.rows, s.r)
		}
	}
	if m.cursor >= len(m.rows) {
		m.cursor = len(m.rows) - 1
	}
	if m.cursor < 0 {
		m.cursor = 0
	}
}

// packContaining returns the pack whose tree holds node (to write it back).
func (m *model) packContaining(node *Node) *pack {
	var has func(n *Node) bool
	has = func(n *Node) bool {
		if n == node {
			return true
		}
		for _, c := range n.Items {
			if has(c) {
				return true
			}
		}
		return false
	}
	for _, p := range m.packs {
		if has(p.root) {
			return p
		}
	}
	return nil
}

func (m *model) findParent(node *Node) *Node {
	var walk func(n *Node) *Node
	walk = func(n *Node) *Node {
		for _, c := range n.Items {
			if c == node {
				return n
			}
			if r := walk(c); r != nil {
				return r
			}
		}
		return nil
	}
	return walk(m.root)
}

// save writes the pack that owns node, then regenerates aliases.sh.
func (m *model) save(node *Node) error {
	if p := m.packContaining(node); p != nil {
		if err := savePack(p); err != nil {
			return err
		}
	}
	return writeAliases(filepath.Join(m.dir, aliasesFileName), m.root)
}

// setAlias sets (or clears, if name is empty) the alias of a command.
func (m *model) setAlias(node *Node, name string) {
	name = strings.TrimSpace(name)
	if name == "" {
		m.delAlias(node)
		return
	}
	if !validAlias(name) {
		m.status = "✗ invalid name (start with letter/_; then letters/digits/_/-/.)"
		return
	}
	if other := m.aliasUsedBy(name, node); other != nil {
		m.status = "✗ alias '" + name + "' already used by '" + other.Name + "'"
		return
	}
	old := node.Alias
	node.Alias = name
	if err := m.save(node); err != nil {
		node.Alias = old
		m.status = "✗ save failed: " + err.Error()
		return
	}
	if m.external[name] {
		m.status = "⚠ alias '" + name + "' set — but it also exists outside cx (may clash)"
	} else {
		m.status = "✓ alias '" + name + "' set  (new shell / source aliases.sh)"
	}
}

func (m *model) delAlias(node *Node) {
	old := node.Alias
	node.Alias = ""
	if err := m.save(node); err != nil {
		node.Alias = old
		m.status = "✗ save failed: " + err.Error()
		return
	}
	m.status = "✓ removed alias '" + old + "'"
}

func (m *model) createCommand(parent *Node, name, desc, cmd, alias string) {
	name, cmd, alias = strings.TrimSpace(name), strings.TrimSpace(cmd), strings.TrimSpace(alias)
	if name == "" || cmd == "" {
		m.status = "✗ name and command are required"
		return
	}
	if alias != "" && !validAlias(alias) {
		m.status = "✗ invalid alias (start with letter/_; then letters/digits/_/-/.)"
		return
	}
	if alias != "" {
		if other := m.aliasUsedBy(alias, nil); other != nil {
			m.status = "✗ alias '" + alias + "' already used by '" + other.Name + "'"
			return
		}
	}
	node := &Node{Name: name, Desc: desc, Cmd: cmd, Alias: alias}
	parent.Items = append(parent.Items, node)
	if err := m.save(parent); err != nil {
		parent.Items = parent.Items[:len(parent.Items)-1]
		m.status = "✗ save failed: " + err.Error()
		return
	}
	m.status = "✓ added '" + name + "'"
	m.recompute()
}

func (m *model) editCommand(node *Node, name, desc, cmd, alias string) {
	name, cmd, alias = strings.TrimSpace(name), strings.TrimSpace(cmd), strings.TrimSpace(alias)
	if name == "" || cmd == "" {
		m.status = "✗ name and command are required"
		return
	}
	if alias != "" && !validAlias(alias) {
		m.status = "✗ invalid alias (start with letter/_; then letters/digits/_/-/.)"
		return
	}
	if alias != "" {
		if other := m.aliasUsedBy(alias, node); other != nil {
			m.status = "✗ alias '" + alias + "' already used by '" + other.Name + "'"
			return
		}
	}
	old := *node
	node.Name, node.Desc, node.Cmd, node.Alias = name, desc, cmd, alias
	if err := m.save(node); err != nil {
		*node = old
		m.status = "✗ save failed: " + err.Error()
		return
	}
	m.status = "✓ saved '" + name + "'"
	m.recompute()
}

// sortPacks keeps top-level packs ordered by filename (matching a fresh load).
func (m *model) sortPacks() {
	sort.Slice(m.packs, func(i, j int) bool { return m.packs[i].file < m.packs[j].file })
	m.root.Items = m.root.Items[:0]
	for _, p := range m.packs {
		m.root.Items = append(m.root.Items, p.root)
	}
}

func (m *model) createCategory(parent *Node, name, desc, icon string) {
	name = strings.TrimSpace(name)
	if name == "" {
		m.status = "✗ name is required"
		return
	}
	node := &Node{Name: name, Desc: strings.TrimSpace(desc), Icon: strings.TrimSpace(icon)}
	if parent == m.root {
		// a top-level category is a new pack file
		file := filepath.Join(m.dir, slug(name)+".yaml")
		if _, err := os.Stat(file); err == nil {
			m.status = "✗ a pack file already exists for that name"
			return
		}
		p := &pack{file: file, root: node}
		if err := savePack(p); err != nil {
			m.status = "✗ save failed: " + err.Error()
			return
		}
		m.packs = append(m.packs, p)
		m.sortPacks()
	} else {
		parent.Items = append(parent.Items, node)
		if err := m.save(parent); err != nil {
			parent.Items = parent.Items[:len(parent.Items)-1]
			m.status = "✗ save failed: " + err.Error()
			return
		}
	}
	m.status = "✓ added category '" + name + "'"
	m.recompute()
}

func (m *model) editCategory(node *Node, name, desc, icon string) {
	name = strings.TrimSpace(name)
	if name == "" {
		m.status = "✗ name is required"
		return
	}
	node.Name, node.Desc, node.Icon = name, strings.TrimSpace(desc), strings.TrimSpace(icon)
	if err := m.save(node); err != nil {
		m.status = "✗ save failed: " + err.Error()
		return
	}
	m.status = "✓ saved category '" + name + "'"
	m.recompute()
}

// deleteNode removes a command or a category. A top-level category deletes its
// whole pack file.
func (m *model) deleteNode(node *Node) {
	for i, p := range m.packs {
		if p.root == node {
			if err := os.Remove(p.file); err != nil {
				m.status = "✗ delete failed: " + err.Error()
				return
			}
			m.packs = append(m.packs[:i], m.packs[i+1:]...)
			m.sortPacks()
			_ = writeAliases(filepath.Join(m.dir, aliasesFileName), m.root)
			m.status = "✓ deleted category '" + node.Name + "'"
			m.recompute()
			return
		}
	}
	parent := m.findParent(node)
	if parent == nil {
		m.status = "✗ cannot delete this"
		return
	}
	out := parent.Items[:0]
	for _, c := range parent.Items {
		if c != node {
			out = append(out, c)
		}
	}
	parent.Items = out
	if err := m.save(parent); err != nil {
		m.status = "✗ save failed: " + err.Error()
		return
	}
	m.status = "✓ deleted '" + node.Name + "'"
	m.recompute()
}

func (m *model) Init() tea.Cmd { return tick() }

func (m *model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tickMsg:
		m.frame++
		return m, tick()
	case tea.WindowSizeMsg:
		m.w, m.h = msg.Width, msg.Height
	case tea.KeyMsg:
		if m.dlg.kind != dlgNone {
			return m.updateDialog(msg)
		}
		m.status = ""
		switch msg.String() {
		case "ctrl+c":
			return m, tea.Quit
		case "up", "ctrl+p":
			if m.cursor > 0 {
				m.cursor--
			}
		case "down":
			if m.cursor < len(m.rows)-1 {
				m.cursor++
			}
		case "enter", "right", "tab":
			if len(m.rows) == 0 {
				break
			}
			r := m.rows[m.cursor]
			if r.node.isLeaf() {
				m.chosen = r.node.Cmd
				return m, tea.Quit
			}
			m.stack = append(m.stack, r.node)
			m.filter, m.cursor = "", 0
			m.recompute()
		case "left", "esc":
			if m.filter != "" {
				m.filter, m.cursor = "", 0
				m.recompute()
			} else if len(m.stack) > 1 {
				m.stack = m.stack[:len(m.stack)-1]
				m.cursor = 0
				m.recompute()
			} else {
				return m, tea.Quit
			}
		case "backspace":
			if m.filter != "" {
				m.filter = m.filter[:len(m.filter)-1]
				m.cursor = 0
				m.recompute()
			} else if len(m.stack) > 1 {
				m.stack = m.stack[:len(m.stack)-1]
				m.cursor = 0
				m.recompute()
			}
		case "ctrl+a": // set / edit the selected command's alias
			m.openAliasDialog()
		case "ctrl+n": // new command in the current category
			m.openNewCmdDialog()
		case "ctrl+g": // new category (sub-category, or a new top-level pack)
			m.openNewCatDialog()
		case "ctrl+e": // edit the selected command or category
			m.openEditDialog()
		case "ctrl+x": // delete the selected command or category (with confirm)
			m.openDeleteDialog()
		default:
			// any printable key (incl. space) extends the search — so you can
			// find "adhoc", "debug" etc. Actions live on the ctrl-keys.
			if msg.Type == tea.KeyRunes || msg.Type == tea.KeySpace {
				m.filter += string(msg.Runes)
				m.cursor = 0
				m.recompute()
			}
		}
	}
	return m, nil
}

func (m *model) selected() *Node {
	if len(m.rows) == 0 {
		return nil
	}
	return m.rows[m.cursor].node
}

func (m *model) openAliasDialog() {
	n := m.selected()
	if n == nil || !n.isLeaf() {
		m.status = "pick a command first (aliases attach to commands)"
		return
	}
	in := n.Alias
	if in == "" {
		in = slug(n.Name)
	}
	m.dlg = dialog{
		kind: dlgAlias, title: "alias for “" + n.Name + "”", node: n,
		fields: []field{
			{kind: fText, label: "alias", value: in, alias: true},
			{kind: fButton, label: "Save", action: "save-alias"},
			{kind: fButton, label: "Cancel", action: "cancel"},
		},
	}
}

// cmdForm builds the four editable fields for a command (blank, or prefilled).
func cmdForm(prefill *Node) []field {
	var name, desc, cmd, alias string
	if prefill != nil {
		name, desc, cmd, alias = prefill.Name, prefill.Desc, prefill.Cmd, prefill.Alias
	}
	return []field{
		{kind: fText, label: "name", value: name},
		{kind: fText, label: "description", value: desc},
		{kind: fText, label: "command", value: cmd},
		{kind: fText, label: "alias", value: alias, alias: true},
	}
}

func (m *model) openNewCmdDialog() {
	parent := m.cur()
	if parent == m.root {
		m.status = "open a category first, then add a command"
		return
	}
	m.dlg = dialog{
		kind: dlgNewCmd, title: "new command in “" + parent.Name + "”", node: parent,
		fields: append(cmdForm(nil),
			field{kind: fButton, label: "Create", action: "create"},
			field{kind: fButton, label: "Cancel", action: "cancel"},
		),
	}
}

// catForm builds the editable fields for a category (blank, or prefilled).
func catForm(prefill *Node) []field {
	var name, desc, icon string
	if prefill != nil {
		name, desc, icon = prefill.Name, prefill.Desc, prefill.Icon
	}
	return []field{
		{kind: fText, label: "name", value: name},
		{kind: fText, label: "description", value: desc},
		{kind: fText, label: "icon", value: icon},
	}
}

func (m *model) openNewCatDialog() {
	parent := m.cur()
	loc := "top level"
	if parent != m.root {
		loc = "“" + parent.Name + "”"
	}
	m.dlg = dialog{
		kind: dlgNewCat, title: "new category in " + loc, node: parent,
		fields: append(catForm(nil),
			field{kind: fButton, label: "Create", action: "create-cat"},
			field{kind: fButton, label: "Cancel", action: "cancel"},
		),
	}
}

// openEditDialog edits the selected node: a command (cmd form) or a category.
func (m *model) openEditDialog() {
	n := m.selected()
	if n == nil {
		m.status = "nothing selected"
		return
	}
	if n.isLeaf() {
		m.dlg = dialog{
			kind: dlgEditCmd, title: "edit “" + n.Name + "”", node: n,
			fields: append(cmdForm(n),
				field{kind: fButton, label: "Save", action: "save-cmd"},
				field{kind: fButton, label: "Cancel", action: "cancel"},
			),
		}
		return
	}
	m.dlg = dialog{
		kind: dlgEditCat, title: "edit category “" + n.Name + "”", node: n,
		fields: append(catForm(n),
			field{kind: fButton, label: "Save", action: "save-cat"},
			field{kind: fButton, label: "Cancel", action: "cancel"},
		),
	}
}

// openDeleteDialog deletes the selected command or category (with confirm).
func (m *model) openDeleteDialog() {
	n := m.selected()
	if n == nil {
		m.status = "nothing selected"
		return
	}
	title := "delete “" + n.Name + "” ?"
	if !n.isLeaf() {
		title = fmt.Sprintf("delete category “%s” (%d items) ?", n.Name, len(n.Items))
	}
	m.dlg = dialog{
		kind: dlgDelCmd, title: title, node: n,
		fields: []field{
			{kind: fButton, label: "Delete", action: "delete"},
			{kind: fButton, label: "Cancel", action: "cancel"},
		},
		focus: 1, // default focus on Cancel
	}
}

func (m *model) dlgFocusMove(delta int) {
	if n := len(m.dlg.fields); n > 0 {
		m.dlg.focus = (m.dlg.focus + delta + n) % n
	}
}

// updateDialog drives any dialog generically: arrows move focus, Enter on a
// button runs its action, typing edits the focused text field.
func (m *model) updateDialog(msg tea.KeyMsg) (tea.Model, tea.Cmd) {
	d := &m.dlg
	f := &d.fields[d.focus]
	switch msg.String() {
	case "esc", "ctrl+c":
		m.dlg = dialog{}
	case "up", "shift+tab":
		m.dlgFocusMove(-1)
	case "down", "tab":
		m.dlgFocusMove(1)
	case "left":
		if f.kind == fButton {
			m.dlgFocusMove(-1)
		}
	case "right":
		if f.kind == fButton {
			m.dlgFocusMove(1)
		}
	case "enter":
		if f.kind == fButton {
			m.dlgAction(f.action)
		} else {
			m.dlgFocusMove(1)
		}
	case "backspace":
		if f.kind == fText && f.value != "" {
			f.value = f.value[:len(f.value)-1]
		}
	default:
		if f.kind == fText && (msg.Type == tea.KeyRunes || msg.Type == tea.KeySpace) {
			f.value += string(msg.Runes)
		}
	}
	return m, nil
}

func (m *model) dlgAction(action string) {
	d := m.dlg
	node := d.node
	m.dlg = dialog{} // close; the operation sets a status message
	switch action {
	case "cancel":
	case "save-alias":
		m.setAlias(node, d.fields[0].value)
	case "create":
		m.createCommand(node, d.fields[0].value, d.fields[1].value, d.fields[2].value, d.fields[3].value)
	case "save-cmd":
		m.editCommand(node, d.fields[0].value, d.fields[1].value, d.fields[2].value, d.fields[3].value)
	case "create-cat":
		m.createCategory(node, d.fields[0].value, d.fields[1].value, d.fields[2].value)
	case "save-cat":
		m.editCategory(node, d.fields[0].value, d.fields[1].value, d.fields[2].value)
	case "delete":
		m.deleteNode(node)
	}
}

// --- view ----------------------------------------------------------------

// --- color system --------------------------------------------------------

// theme is cx's color system: swap the whole look via $CX_THEME. Every style is
// derived from these roles, so a new theme is just a new set of hex colors.
type theme struct {
	name                                string
	base, surf, text, sub               string
	accent, accent2, green, yellow, red string
	grad                                []string // gradient anchors for the animated logo
}

var themes = map[string]theme{
	"mocha": {
		name: "mocha", base: "#1e1e2e", surf: "#313244", text: "#cdd6f4", sub: "#6c7086",
		accent: "#89b4fa", accent2: "#cba6f7", green: "#a6e3a1", yellow: "#f9e2af", red: "#f38ba8",
		grad: []string{"#89b4fa", "#cba6f7", "#f38ba8", "#fab387", "#a6e3a1", "#94e2d5"},
	},
	"tokyonight": {
		name: "tokyonight", base: "#1a1b26", surf: "#292e42", text: "#c0caf5", sub: "#565f89",
		accent: "#7aa2f7", accent2: "#bb9af7", green: "#9ece6a", yellow: "#e0af68", red: "#f7768e",
		grad: []string{"#7aa2f7", "#bb9af7", "#f7768e", "#ff9e64", "#9ece6a", "#7dcfff"},
	},
	"latte": {
		name: "latte", base: "#eff1f5", surf: "#ccd0da", text: "#4c4f69", sub: "#8c8fa1",
		accent: "#1e66f5", accent2: "#8839ef", green: "#40a02b", yellow: "#df8e1d", red: "#d20f39",
		grad: []string{"#1e66f5", "#8839ef", "#d20f39", "#fe640b", "#40a02b", "#179299"},
	},
}

func pickTheme(name string) theme {
	if t, ok := themes[strings.ToLower(name)]; ok {
		return t
	}
	return themes["mocha"]
}

// styles, assigned by applyTheme.
var (
	stTitle, stCrumb, stCrumbCur, stSep, stSel, stName, stGroup, stGIcon, stLIcon,
	stDesc, stCount, stCmd, stTitleBig, stHelp, stKey, stWarn, stPrompt, stOK,
	stBox, stListBox, stCur lipgloss.Style
	gradRamp []lipgloss.Color
)

func applyTheme(t theme) {
	C := func(s string) lipgloss.Color { return lipgloss.Color(s) }
	base, surf, text, sub := C(t.base), C(t.surf), C(t.text), C(t.sub)
	acc, acc2, green, yellow, red := C(t.accent), C(t.accent2), C(t.green), C(t.yellow), C(t.red)

	stTitle = lipgloss.NewStyle().Foreground(base).Background(acc2).Bold(true).Padding(0, 1)
	stCrumb = lipgloss.NewStyle().Foreground(acc).Bold(true)
	stCrumbCur = lipgloss.NewStyle().Foreground(acc2).Bold(true)
	stSep = lipgloss.NewStyle().Foreground(sub)
	stSel = lipgloss.NewStyle().Foreground(base).Background(acc).Bold(true)
	stName = lipgloss.NewStyle().Foreground(text)
	stGroup = lipgloss.NewStyle().Foreground(acc)
	stGIcon = lipgloss.NewStyle().Foreground(yellow)
	stLIcon = lipgloss.NewStyle().Foreground(green)
	stDesc = lipgloss.NewStyle().Foreground(sub)
	stCount = lipgloss.NewStyle().Foreground(sub)
	stCmd = lipgloss.NewStyle().Foreground(green)
	stTitleBig = lipgloss.NewStyle().Foreground(acc2).Bold(true)
	stHelp = lipgloss.NewStyle().Foreground(sub)
	stKey = lipgloss.NewStyle().Foreground(acc2).Bold(true)
	stWarn = lipgloss.NewStyle().Foreground(red).Bold(true)
	stPrompt = lipgloss.NewStyle().Foreground(yellow)
	stOK = lipgloss.NewStyle().Foreground(green).Bold(true)
	stCur = lipgloss.NewStyle().Foreground(acc2)
	stBox = lipgloss.NewStyle().Border(lipgloss.RoundedBorder()).BorderForeground(surf).Padding(0, 1)
	stListBox = lipgloss.NewStyle().Border(lipgloss.RoundedBorder()).BorderForeground(surf).Padding(0, 1)
	gradRamp = buildRamp(t.grad, 72)
}

// --- gradient helpers -----------------------------------------------------

func parseHex(s string) (r, g, b int) {
	s = strings.TrimPrefix(s, "#")
	if len(s) != 6 {
		return 200, 200, 200
	}
	v, _ := strconv.ParseInt(s, 16, 32)
	return int(v>>16) & 0xff, int(v>>8) & 0xff, int(v) & 0xff
}

func mix(a, b string, t float64) lipgloss.Color {
	ar, ag, ab := parseHex(a)
	br, bg, bb := parseHex(b)
	lp := func(x, y int) int { return int(float64(x) + float64(y-x)*t) }
	return lipgloss.Color(fmt.Sprintf("#%02x%02x%02x", lp(ar, br), lp(ag, bg), lp(ab, bb)))
}

// buildRamp makes a seamless cyclic gradient of n colors through the anchors.
func buildRamp(anchors []string, n int) []lipgloss.Color {
	if len(anchors) < 2 {
		anchors = []string{"#89b4fa", "#cba6f7"}
	}
	out := make([]lipgloss.Color, n)
	for i := 0; i < n; i++ {
		p := float64(i) / float64(n) * float64(len(anchors))
		k := int(p) % len(anchors)
		k2 := (k + 1) % len(anchors)
		out[i] = mix(anchors[k], anchors[k2], p-float64(int(p)))
	}
	return out
}

// gradientText paints each rune along the animated gradient ramp.
func gradientText(s string, frame int) string {
	if len(gradRamp) == 0 {
		return s
	}
	var b strings.Builder
	for i, r := range []rune(s) {
		c := gradRamp[((i*2+frame)%len(gradRamp)+len(gradRamp))%len(gradRamp)]
		b.WriteString(lipgloss.NewStyle().Foreground(c).Bold(true).Render(string(r)))
	}
	return b.String()
}

var logoArt = []string{
	"╔═╗═╗ ╦",
	"║  ╔╩╦╝",
	"╚═╝╩ ╚═",
}

func (m *model) logo() []string {
	out := make([]string, len(logoArt))
	for i, l := range logoArt {
		out[i] = gradientText(l, m.frame+i*4)
	}
	return out
}

func key(k, label string) string { return stKey.Render(k) + " " + stHelp.Render(label) }

func (m *model) breadcrumb() string {
	crumb := ""
	for i, n := range m.stack {
		name := n.Name
		if i == 0 {
			name = "home"
		}
		st := stCrumb
		if i == len(m.stack)-1 {
			st = stCrumbCur
		}
		if i > 0 {
			crumb += stSep.Render(" ")
		}
		crumb += st.Render(name)
	}
	if m.filter != "" {
		crumb += "   " + stPrompt.Render(" "+m.filter)
	}
	return crumb
}

func (m *model) View() string {
	// header: animated logo + subtitle + breadcrumb
	lg := m.logo()
	sub := stDesc.Render("command library") + stSep.Render(" · ") + stDesc.Render("shortcut manager")
	header := lg[0] + "\n" +
		lg[1] + "   " + sub + "\n" +
		lg[2] + "   " + m.breadcrumb()

	listW := m.w/2 - 5
	if listW < 20 {
		listW = 20
	}
	prevW := m.w - listW - 9
	if prevW < 16 {
		prevW = 16
	}
	innerH := m.h - 9
	if innerH < 3 {
		innerH = 3
	}

	start := 0
	if m.cursor >= innerH {
		start = m.cursor - innerH + 1
	}
	end := start + innerH
	if end > len(m.rows) {
		end = len(m.rows)
	}

	var b strings.Builder
	if len(m.rows) == 0 {
		b.WriteString(stDesc.Render("(nichts gefunden)"))
	}
	for i := start; i < end; i++ {
		r := m.rows[i]
		g := r.node.glyph()
		label := r.node.Name
		if m.filter != "" && r.path != "" {
			label = r.path
		}
		badge := ""
		if r.node.isLeaf() && r.node.Alias != "" {
			badge = " [" + r.node.Alias + "]"
		}
		if i == m.cursor {
			line := " " + g + "  " + label + badge
			if r.isGroup {
				line += fmt.Sprintf("  (%d)", len(r.node.Items))
			}
			b.WriteString(stSel.Width(listW).Render(truncate(line, listW-1)))
		} else {
			icon, nst := stLIcon, stName
			if r.isGroup {
				icon, nst = stGIcon, stGroup
			}
			avail := listW - 9 - len([]rune(badge))
			seg := " " + icon.Render(g) + "  " + nst.Render(truncate(label, avail))
			switch {
			case r.isGroup:
				seg += stCount.Render(fmt.Sprintf("  (%d)", len(r.node.Items)))
			case badge != "":
				seg += stCur.Render(badge)
			}
			b.WriteString(seg)
		}
		if i < end-1 {
			b.WriteByte('\n')
		}
	}
	listPanel := stListBox.Width(listW).Height(innerH).Render(b.String())

	var pb strings.Builder
	if len(m.rows) > 0 {
		sel := m.rows[m.cursor].node
		iconSt := stLIcon
		if !sel.isLeaf() {
			iconSt = stGIcon
		}
		pb.WriteString(iconSt.Render(sel.glyph()) + "  " + stTitleBig.Render(sel.Name))
		if !sel.isLeaf() {
			pb.WriteString("  " + stCount.Render(fmt.Sprintf("%d items", len(sel.Items))))
		}
		if sel.isLeaf() && sel.Alias != "" {
			pb.WriteString("  " + stCur.Render("["+sel.Alias+"]"))
		}
		pb.WriteString("\n\n")
		if sel.Desc != "" {
			pb.WriteString(stDesc.Width(prevW).Render(sel.Desc) + "\n")
		}
		if sel.isLeaf() {
			pb.WriteString("\n" + stCmd.Render("❯") + " " + stCmd.Width(prevW-3).Render(sel.Cmd))
			if sel.Alias != "" {
				pb.WriteString("\n\n" + stDesc.Render("alias ") + stCur.Render(sel.Alias))
			}
		}
	}
	prevPanel := stBox.Width(prevW).Height(innerH).Render(pb.String())

	body := lipgloss.JoinHorizontal(lipgloss.Top, listPanel, " ", prevPanel)

	// footer: status / help
	var footer string
	switch {
	case m.status != "":
		footer = stOK.Render(m.status)
	default:
		footer = strings.Join([]string{
			key("↑↓", "move"), key("→", "open"), key("←", "back"), key("type", "search"),
			key("^n", "cmd"), key("^g", "cat"), key("^e", "edit"), key("^a", "alias"), key("^x", "del"),
			key("⏎", "pick"), key("esc", "quit"),
		}, stSep.Render(" · "))
	}

	base := header + "\n\n" + body + "\n" + footer
	if m.dlg.kind != dlgNone {
		return overlayCenter(base, m.renderDialog(), m.w)
	}
	return base
}

// renderDialog builds the active modal popup box.
func (m *model) renderDialog() string {
	d := m.dlg
	w := 60
	if w > m.w-6 {
		w = m.w - 6
	}
	if w < 28 {
		w = 28
	}
	var c strings.Builder
	c.WriteString(stTitleBig.Render(" "+d.title) + "\n\n")
	for i, f := range d.fields {
		focused := i == d.focus
		switch f.kind {
		case fText:
			if focused {
				plain := " " + f.label + ": " + f.value + "▏"
				c.WriteString(stSel.Width(w).Render(truncate(plain, w-1)))
			} else {
				c.WriteString(" " + stDesc.Render(f.label+": ") +
					stName.Render(truncate(f.value, w-len(f.label)-4)))
			}
			c.WriteByte('\n')
			if f.alias {
				c.WriteString("   " + m.aliasHint(f.value) + "\n")
			}
		case fButton:
			if focused {
				c.WriteString(stSel.Width(w).Render(" ▸ " + f.label))
			} else {
				c.WriteString("   " + stKey.Render(f.label))
			}
			c.WriteByte('\n')
		}
	}
	c.WriteString("\n" + stHelp.Render("↑↓ move · ⏎ activate · esc cancel"))
	return lipgloss.NewStyle().
		Border(lipgloss.RoundedBorder()).BorderForeground(stCur.GetForeground()).
		Padding(1, 2).Width(w).Render(c.String())
}

func (m *model) aliasHint(val string) string {
	switch m.nameStatus(val, m.dlg.node) {
	case "current":
		return stDesc.Render("↺ unchanged")
	case "dup":
		return stWarn.Render("⚠ used by another command")
	case "conflict":
		return stWarn.Render("⚠ also an alias outside cx")
	case "new":
		return stOK.Render("✓ free")
	default:
		if strings.TrimSpace(val) != "" {
			return stWarn.Render("✗ invalid")
		}
		return stDesc.Render("optional")
	}
}

// overlayCenter splices a box centered over the base view (nvim-style popup).
// It centers within the base's OWN height and never grows the frame — padding
// out to the full terminal height would overflow it, scroll, and drop the
// footer line when the dialog closes.
func overlayCenter(base, box string, w int) string {
	if w <= 0 {
		return box
	}
	bl := strings.Split(base, "\n")
	boxLines := strings.Split(box, "\n")
	top := (len(bl) - len(boxLines)) / 2
	if top < 0 {
		// base shorter than the box: grow just enough, no more
		for len(bl) < len(boxLines) {
			bl = append(bl, "")
		}
		top = 0
	}
	left := (w - lipgloss.Width(box)) / 2
	if left < 0 {
		left = 0
	}
	pad := strings.Repeat(" ", left)
	for i, ln := range boxLines {
		if y := top + i; y >= 0 && y < len(bl) {
			bl[y] = pad + ln
		}
	}
	return strings.Join(bl, "\n")
}

func truncate(s string, w int) string {
	r := []rune(s)
	if len(r) <= w || w <= 1 {
		return s
	}
	return string(r[:w-1]) + "…"
}

// --- flat listing (non-TUI) ---------------------------------------------

func printList(n *Node, prefix string) {
	for _, c := range n.Items {
		p := c.Name
		if prefix != "" {
			p = prefix + " › " + c.Name
		}
		if c.isLeaf() {
			fmt.Printf("%-50s  %s\n", p, c.Cmd)
		} else {
			printList(c, p)
		}
	}
}

func resolveDir() string {
	if d := os.Getenv("CX_DIR"); d != "" {
		return d
	}
	cfg, _ := os.UserConfigDir()
	return filepath.Join(cfg, "cx")
}

// parseExternal turns $CX_ALIASES (alias names the shell wrapper collected from
// the live shell) into a set, so cx can flag name clashes independent of its
// own config.
func parseExternal(s string) map[string]bool {
	set := map[string]bool{}
	for _, f := range strings.Fields(s) {
		set[f] = true
	}
	return set
}

// rootFromPacks builds the synthetic root whose Items are the pack categories.
func rootFromPacks(packs []*pack) *Node {
	root := &Node{Name: "cx"}
	for _, p := range packs {
		root.Items = append(root.Items, p.root)
	}
	return root
}

func main() {
	dir := resolveDir()

	// subcommand: (re)generate aliases.sh from the packs
	if len(os.Args) > 1 && os.Args[1] == "--gen-aliases" {
		packs, err := loadPacks(dir)
		if err != nil {
			fmt.Fprintln(os.Stderr, "cx:", err)
			os.Exit(1)
		}
		if err := writeAliases(filepath.Join(dir, aliasesFileName), rootFromPacks(packs)); err != nil {
			fmt.Fprintln(os.Stderr, "cx:", err)
			os.Exit(1)
		}
		return
	}

	packs, err := loadPacks(dir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "cx: cannot read command packs from %s: %v\n", dir, err)
		os.Exit(1)
	}
	root := rootFromPacks(packs)

	if len(root.Items) == 0 {
		fmt.Fprintf(os.Stderr, "cx: no packs found in %s (add some *.yaml files)\n", dir)
		os.Exit(1)
	}

	if len(os.Args) > 1 && (os.Args[1] == "--list" || os.Args[1] == "-l") {
		printList(root, "")
		return
	}

	// The wrapper captures stdout (it's a pipe), so lipgloss' default detection
	// would see "no TTY" and strip all color. Detect from stderr — the real
	// terminal the TUI renders to — and force that profile.
	lipgloss.SetColorProfile(termenv.NewOutput(os.Stderr).ColorProfile())
	applyTheme(pickTheme(os.Getenv("CX_THEME")))

	external := parseExternal(os.Getenv("CX_ALIASES"))
	p := tea.NewProgram(newModel(root, dir, packs, external), tea.WithAltScreen(), tea.WithOutput(os.Stderr))
	res, err := p.Run()
	if err != nil {
		fmt.Fprintln(os.Stderr, "cx:", err)
		os.Exit(1)
	}
	if mm, ok := res.(*model); ok && mm.chosen != "" {
		fmt.Print(mm.chosen)
	}
}
