---
name: CI

"on":
  push:
    branches: [main]
    paths-ignore: ["mise/**"]
  pull_request:
    paths-ignore: ["mise/**"]

jobs:
  flake-check:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          docker-images: false
          swap-storage: false

      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@main

      - name: nix flake check
        run: nix flake check --no-build

  build:
    name: Build ${{ matrix.host }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: [x230, xps17]
    steps:
      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          docker-images: false
          swap-storage: false

      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@main

      - name: Build nixosConfigurations.${{ matrix.host }}
        run: nix build ".#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel" --no-link
