---
name: CI

"on":
  push:
    branches: [main]
  pull_request:

jobs:
  flake-check:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: nix flake check
        run: nix flake check --no-build

  build:
    name: Build ${{ matrix.host }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: [main, t230, vm-test]
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build nixosConfigurations.${{ matrix.host }}
        run: nix build ".#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel" --no-link
